### ISSUE TITLE
Integration test fails with default template for node

### ISSUE THREAD

**Issue by fc7** [knative/func#1526]
When I run the following: 
```
kn func create -l node foo
cd foo
npm i
npm test
```
I get this error
```
> http-handler@0.1.0 test
> node test/unit.js && node test/integration.js

TAP version 13
# Unit: handles an HTTP GET
{
  "log": {},
  "method": "GET",
  "query": {
    "name": "tiger"
  }
}
ok 1 should be deeply equivalent
# Unit: handles an HTTP POST
{
  "log": {},
  "method": "POST",
  "body": {
    "name": "tiger"
  }
}
ok 2 should be deeply equivalent
# Unit: responds with error code if neither GET or POST
{
  "log": {}
}
ok 3 should be deeply equivalent

1..3
# tests 3
# pass  3

# ok

TAP version 13
# Integration: handles an HTTP GET
not ok 1 No error
  ---
    operator: error
    at: Test.<anonymous> (/Users/fc7/dev/foo/test/integration.js:22:11)
    stack: |-
      SyntaxError: Unexpected token H in JSON at position 0
          at JSON.parse (<anonymous>)
          at IncomingMessage.<anonymous> (/Users/fc7/dev/foo/node_modules/superagent/lib/node/parsers/json.js:11:35)
          at IncomingMessage.emit (node:events:525:35)
          at endReadableNT (node:internal/streams/readable:1359:12)
          at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
  ...
/Users/fc7/dev/foo/test/integration.js:23
        t.deepEqual(res.body, { query: { name: 'tiger' } });
                        ^

TypeError: Cannot read properties of undefined (reading 'body')
    at Test.<anonymous> (/Users/fc7/dev/foo/test/integration.js:23:25)
    at Test.assert (/Users/fc7/dev/foo/node_modules/supertest/lib/test.js:181:6)
    at localAssert (/Users/fc7/dev/foo/node_modules/supertest/lib/test.js:131:12)
    at /Users/fc7/dev/foo/node_modules/supertest/lib/test.js:128:5
    at Request.callback (/Users/fc7/dev/foo/node_modules/superagent/lib/node/index.js:728:3)
    at /Users/fc7/dev/foo/node_modules/superagent/lib/node/index.js:911:25
    at IncomingMessage.<anonymous> (/Users/fc7/dev/foo/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Note that the function can be built, run and invoked correctly. However there is an issue with the provided integration test, which is likely to somehow scare off new users. I was thinking it could be due to an incompatible version of the `supertest` library or  dependencies, as my `package-lock.json` looked different than the one in [this repo](https://github.com/knative/func/blob/main/templates/node/http/package-lock.json#L16) but even after running `npm ci` with yours, I have the same error.

I tried the following versions of `kn func` and `func` and the issue is present with all of them, presumably because they all fetch the same template for `-l node`:
* kn v1.5.0 and v1.8.1
* func v1.8.2

node v18.3.0 and npm v8.19.3

**Comment by lance** [comment]
Odd. I can't recreate this.

```
func --version
v1.8.2
rm -rf * .*
zsh: sure you want to delete all 7 files in /Users/lball/demo/test [yn]? y
func --version
v1.8.2
node --version
v18.10.0
func create -l node
Created node function in /Users/lball/demo/test
npm install && npm test
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 216 packages, and audited 217 packages in 689ms

54 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (2 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> http-handler@0.1.0 test
> node test/unit.js && node test/integration.js

TAP version 13
# Unit: handles an HTTP GET
{
  "log": {},
  "method": "GET",
  "query": {
    "name": "tiger"
  }
}
ok 1 should be deeply equivalent
# Unit: handles an HTTP POST
{
  "log": {},
  "method": "POST",
  "body": {
    "name": "tiger"
  }
}
ok 2 should be deeply equivalent
# Unit: responds with error code if neither GET or POST
{
  "log": {}
}
ok 3 should be deeply equivalent

1..3
# tests 3
# pass  3

# ok

TAP version 13
# Integration: handles an HTTP GET
ok 1 No error
ok 2 should be deeply equivalent
# Integration: handles an HTTP POST
ok 3 No error
ok 4 should be deeply equivalent
# Integration: responds with error code if neither GET or POST
ok 5 should be deeply equivalent

1..5
# tests 5
# pass  5

# ok
```

**Comment by lance** [comment]
I also tried with Node.js 18.2 with no error. Hmm.

**Comment by matejvasek** [comment]
@fc7 by any chance: don't you have anything running on tcp/8080?

**Comment by matejvasek** [comment]
What is your os/arch/node?

**Comment by matejvasek** [comment]
@fc7 could your please try adding debug line 
```js
test('Integration: handles an HTTP GET', t => {
  start(func).then(server => {
    t.plan(2);
    request(server)
      .get('/?name=tiger')
      .expect(200)
      .expect('Content-Type', /json/)
      .end((err, res) => {
        t.error(err, 'No error');
        console.log(res.body); // <-- print this
        t.deepEqual(res.body, { query: { name: 'tiger' } });
        t.end();
        server.close();
      });
  }, errHandler(t));
});
```

**Comment by lance** [comment]
Please put the `console.log()` line _above_ the `t.error(err, 'No error')` line.

```
        console.log(res.body); // <-- print this
        t.error(err, 'No error');
```

**Comment by fc7** [comment]
> What is your os/arch/node?
macOS/x86_64/18.3.0

I have tried again after rebooting my Macbook and the problem can no longer be reproduced. Very odd, but probably @matejvasek is right and unknowingly I had a container running with podman in the background with port 8080 exposed, which interfered with the test. I will thus close this. Thanks for your help!

**Comment by matejvasek** [comment]
>. Very odd, but probably @matejvasek is right and unknowingly I had a container running with podman in the background with port 8080 exposed,

@fc7 I think something else had to be wrong, if there was something occupying port the error message would say that.
