### ISSUE TITLE
make tests hanging, SIGSEGV when interrupted with Ctl-c

### ISSUE THREAD

**Issue by aslom** [knative/func#1801]
Running `make tests` hangs for minutes (that is how long I waited)  - I do not think it is normal?

When I press Ctrl-C I get all kinds output including SIGSEGV - not sure how to interpret it?

How do you find out which test is failing and what causing it?

This is in main branch and on Macbook Pro M1 (details below)

```
aslom@m1:~/Documents/awsm/go/src/github.com/knative/func|main⚡ ⇒  make test
# Removing temporary template files
go generate pkg/functions/templates_embedded.go
go test -race -cover -coverprofile=coverage.txt ./...
?   	knative.dev/func/cmd/func	[no test files]
?   	knative.dev/func/cmd/prompt	[no test files]
?   	knative.dev/func/docs/generator	[no test files]
?   	knative.dev/func/generate	[no test files]
?   	knative.dev/func/generate/templates	[no test files]
?   	knative.dev/func/pkg/git/github	[no test files]
?   	knative.dev/func/pkg/git/gitlab	[no test files]
?   	knative.dev/func/pkg/k8s/labels	[no test files]
?   	knative.dev/func/pkg/mock	[no test files]
?   	knative.dev/func/pkg/openshift	[no test files]
?   	knative.dev/func/pkg/pipelines	[no test files]
ok  	knative.dev/func/cmd	8.547s	coverage: 45.5% of statements
ok  	knative.dev/func/cmd/templates	0.701s	coverage: 81.5% of statements
ok  	knative.dev/func/pkg/builders	0.328s	coverage: 88.0% of statements
ok  	knative.dev/func/pkg/builders/buildpacks	1.125s	coverage: 45.7% of statements
ok  	knative.dev/func/pkg/builders/s2i	0.373s	coverage: 71.0% of statements
ok  	knative.dev/func/pkg/config	1.769s	coverage: 88.1% of statements
ok  	knative.dev/func/pkg/docker	6.915s	coverage: 84.3% of statements
?   	knative.dev/func/pkg/pipelines/tekton/pac	[no test files]
?   	knative.dev/func/pkg/progress	[no test files]
?   	knative.dev/func/pkg/random	[no test files]
?   	knative.dev/func/pkg/ssh	[no test files]
?   	knative.dev/func/pkg/testing	[no test files]
?   	knative.dev/func/plugin	[no test files]
?   	knative.dev/func/schema/generator	[no test files]
?   	knative.dev/func/test/common	[no test files]
?   	knative.dev/func/test/oncluster	[no test files]
?   	knative.dev/func/test/testhttp	[no test files]
ok  	knative.dev/func/pkg/docker/creds	15.779s	coverage: 81.3% of statements
ok  	knative.dev/func/pkg/filesystem	38.472s	coverage: 79.3% of statements
^Cmkdir -p /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/builds/by-hash/caccc9242ae944f8fd4de1cc3b27aab537b9d328625842364ec1426a3258d9c7
mkdir -p /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/builds/by-pid
ln -s ../by-hash/caccc9242ae944f8fd4de1cc3b27aab537b9d328625842364ec1426a3258d9c7 /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/builds/by-pid/40749
→ /func
→ /func/README.md
→ /func/func.yaml
→ /func/go.mod
→ /func/handle.go
→ /func/handle_test.go
mv ./datalayer.tar.gz ./oci/blobs/sha256/4646fc772f5af5b636fac57021b911cf711c67ebb3863f7844d46c7e522b68f4
go build -o /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/builds/by-hash/caccc9242ae944f8fd4de1cc3b27aab537b9d328625842364ec1426a3258d9c7/result/f.linux.amd64
→ /func/f
  wrote 6707226 bytes
mv ./execlayer.linux.amd64.tar.gz ./oci/blobs/sha256/65b6ec0350458174b2697bdc4f075601122aa14d438ad0640d3620d47832dcf4
mv ./config.json ./oci/blobs/sha256/5d7da309d55c2f0346616a1181e602f10fa450744d5f7693c98395b005bbfb3d
mv image.linux.amd64.json ./oci/blobs/sha256/2fe8b850cae0913c801495b76193b812ea40c8ad46c7e2ca9a08b90de59cd9b1
go build -o /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/builds/by-hash/caccc9242ae944f8fd4de1cc3b27aab537b9d328625842364ec1426a3258d9c7/result/f.linux.arm64
→ /func/f
  wrote 6377840 bytes
mv ./execlayer.linux.arm64.tar.gz ./oci/blobs/sha256/f51db501670a9624999126f7364d18836b55c253771aa0f8c70165a2d2a5c7b1
mv ./config.json ./oci/blobs/sha256/e12f16fb305ba134dc2ea6fc2b17b9a99b7f85449ecc74bc4f14a7a5f1de62a9
mv image.linux.arm64.json ./oci/blobs/sha256/80a6146cbb6488fdf44e04623eeb2993e3aee406575c47b25e9f9feada6cb24b
go build -o /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/builds/by-hash/caccc9242ae944f8fd4de1cc3b27aab537b9d328625842364ec1426a3258d9c7/result/f.linux.arm.v7
→ /func/f
  wrote 6548537 bytes
mv ./execlayer.linux.arm.tar.gz ./oci/blobs/sha256/ec0a059dafe20c869246a7ff0e1c5919b9dcc8f8f3047a9732c7c3d9e397c1f4
mv ./config.json ./oci/blobs/sha256/675e5e408170622a52494f869ad72a3f9ba3d64d925027b7cfeb92ba25b4cc8d
mv image.linux.arm.json ./oci/blobs/sha256/4e7b0a207e240bdeaf5b218b4b261fb3812b60ab3b8ed440c8ad12a5144c1e05
ln -s /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/builds/by-hash/caccc9242ae944f8fd4de1cc3b27aab537b9d328625842364ec1426a3258d9c7 /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/builds/last
mkdir -p /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/runs/54438
cd /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/runs/54438 && go build -o f.bin
f
s
cd /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001 && PORT=54438 /var/folders/01/lr6391qn4ps7fr70xypbbz1w0000gn/T/TestClient_Runner4024200626/001/.func/runs/54438/f.bin
Waiting for http://127.0.0.1:54438//health/readiness
--- FAIL: TestClient_Runner (16.32s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105454d38]

goroutine 290 [running]:
testing.tRunner.func1.2({0x1057ee9c0, 0x105ebd9c0})
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:1526 +0x278
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:1529 +0x448
panic({0x1057ee9c0, 0x105ebd9c0})
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/panic.go:890 +0x258
knative.dev/func/pkg/functions.waitFor(0xc00015a480, 0xc000030be0?)
	/Users/aslom/Documents/awsm/go/src/github.com/knative/func/pkg/functions/runner.go:170 +0x2e8
knative.dev/func/pkg/functions.(*defaultRunner).Run(_, {_, _}, {{0xc00022bb6a, 0x6}, {0xc000040870, 0x50}, {0xc00022bb8d, 0x3}, {0x0, ...}, ...})
	/Users/aslom/Documents/awsm/go/src/github.com/knative/func/pkg/functions/runner.go:72 +0x230
knative.dev/func/pkg/functions.(*Client).Run(_, {_, _}, {{0xc00022bb6a, 0x6}, {0xc000040870, 0x50}, {0xc00022bb8d, 0x3}, {0x0, ...}, ...})
	/Users/aslom/Documents/awsm/go/src/github.com/knative/func/pkg/functions/client.go:845 +0x2e0
knative.dev/func/pkg/functions_test.TestClient_Runner(0xc00024d380)
	/Users/aslom/Documents/awsm/go/src/github.com/knative/func/pkg/functions/client_test.go:662 +0x48c
testing.tRunner(0xc00024d380, 0x1058d9648)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:1576 +0x18c
created by testing.(*T).Run
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:1629 +0x5e8
2023/06/08 13:02:39 Listening on port 54438
2023/06/08 13:03:41 Signal 'window size changes' ignored.
2023/06/08 13:03:42 Signal 'interrupt' received. Stopping.
2023/06/08 13:03:42 Signal 'urgent I/O condition' ignored.
FAIL	knative.dev/func/pkg/functions	82.227s
make: *** [test] Error 1

aslom@m1:~/Documents/awsm/go/src/github.com/knative/func|main⚡ ⇒  git pull
Already up to date.
aslom@m1:~/Documents/awsm/go/src/github.com/knative/func|main⚡ ⇒  git rev-parse --abbrev-ref HEAD
main
aslom@m1:~/Documents/awsm/go/src/github.com/knative/func|main⚡ ⇒  git rev-parse HEAD
6b97fb5a3cfad3624f241d0168a91942ea06cb4a
aslom@m1:~/Documents/awsm/go/src/github.com/knative/func|main⚡ ⇒  go version
go version go1.20.4 darwin/arm64
aslom@m1:~/Documents/awsm/go/src/github.com/knative/func|main⚡ ⇒  uname -a
Darwin m1.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Apr 24 21:11:17 PDT 2023; root:xnu-8020.240.18.701.5~1/RELEASE_ARM64_T6000 arm64
```

**Comment by aslom** [comment]
Based on @matejvasek sugestions I moved defer to be after erro check and make test works now for me
https://github.com/knative/func/pull/1790/files#diff-1d34d45077da07300c13cb45560f9d4633f80690f08868fc39661b7b00710813R160-R162

after changes
```
aslom@m1:~/Documents/awsm/go/src/github.com/knative/func-aslom|defer-close-after-error-more-diag⚡ ⇒  time make test
# Removing temporary template files
go generate pkg/functions/templates_embedded.go
go test -race -cover -coverprofile=coverage.txt ./...
?   	knative.dev/func/cmd/func	[no test files]
?   	knative.dev/func/cmd/prompt	[no test files]
?   	knative.dev/func/docs/generator	[no test files]
?   	knative.dev/func/generate	[no test files]
?   	knative.dev/func/generate/templates	[no test files]
?   	knative.dev/func/pkg/git/github	[no test files]
?   	knative.dev/func/pkg/git/gitlab	[no test files]
?   	knative.dev/func/pkg/k8s/labels	[no test files]
ok  	knative.dev/func/cmd	7.463s	coverage: 45.5% of statements
ok  	knative.dev/func/cmd/templates	0.474s	coverage: 81.5% of statements
ok  	knative.dev/func/pkg/builders	1.809s	coverage: 88.0% of statements
ok  	knative.dev/func/pkg/builders/buildpacks	1.823s	coverage: 45.7% of statements
ok  	knative.dev/func/pkg/builders/s2i	1.488s	coverage: 71.0% of statements
ok  	knative.dev/func/pkg/config	2.192s	coverage: 88.1% of statements
ok  	knative.dev/func/pkg/docker	5.776s	coverage: 84.3% of statements
?   	knative.dev/func/pkg/mock	[no test files]
?   	knative.dev/func/pkg/openshift	[no test files]
?   	knative.dev/func/pkg/pipelines	[no test files]
?   	knative.dev/func/pkg/pipelines/tekton/pac	[no test files]
?   	knative.dev/func/pkg/progress	[no test files]
?   	knative.dev/func/pkg/random	[no test files]
?   	knative.dev/func/pkg/ssh	[no test files]
?   	knative.dev/func/pkg/testing	[no test files]
?   	knative.dev/func/test/common	[no test files]
?   	knative.dev/func/schema/generator	[no test files]
?   	knative.dev/func/plugin	[no test files]
?   	knative.dev/func/test/oncluster	[no test files]
?   	knative.dev/func/test/testhttp	[no test files]
ok  	knative.dev/func/pkg/docker/creds	14.719s	coverage: 81.3% of statements
ok  	knative.dev/func/pkg/filesystem	37.274s	coverage: 79.3% of statements
ok  	knative.dev/func/pkg/functions	35.187s	coverage: 78.0% of statements
ok  	knative.dev/func/pkg/git	0.496s	coverage: 52.5% of statements
ok  	knative.dev/func/pkg/http	0.549s	coverage: 82.5% of statements
ok  	knative.dev/func/pkg/k8s	0.805s	coverage: 13.2% of statements
ok  	knative.dev/func/pkg/knative	0.950s	coverage: 3.3% of statements
ok  	knative.dev/func/pkg/oci	37.840s	coverage: 77.9% of statements
ok  	knative.dev/func/pkg/pipelines/tekton	1.584s	coverage: 29.3% of statements
ok  	knative.dev/func/pkg/scaffolding	0.933s	coverage: 91.7% of statements
ok  	knative.dev/func/pkg/utils	0.681s	coverage: 61.1% of statements
make test  156.66s user 20.28s system 316% cpu 55.907 total
````
