### ISSUE TITLE
func subscribe: panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by matzew** [knative/func#2567]
Running `func subscribe`

and than `func subscribe` with `--filter` argument(s) causes **panic: assignment to entry in nil map**

 ```
$GOPATH/src/knative.dev/func/func subscribe --filter type=org.apache.camel.event.aws.s3.getObject
panic: assignment to entry in nil map

goroutine 1 [running]:
knative.dev/func/cmd.updateOrAddSubscription({0xc000a6a318, 0x1, 0x1}, {{0xc000a7a2d0, 0x1, 0x1}, {0x2e78a0b, 0x7}})
	/home/matzew/go/src/knative.dev/func/cmd/subscribe.go:100 +0x236
knative.dev/func/cmd.runSubscribe(0x0?)
	/home/matzew/go/src/knative.dev/func/cmd/subscribe.go:64 +0x3ab
knative.dev/func/cmd.NewSubscribeCmd.func1(0xc0009f0608?, {0x2e73df0?, 0x4?, 0x2e73e7c?})
	/home/matzew/go/src/knative.dev/func/cmd/subscribe.go:33 +0x13
github.com/spf13/cobra.(*Command).execute(0xc0009f0608, {0xc000a56de0, 0x2, 0x2})
	/home/matzew/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc00091a008)
	/home/matzew/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/matzew/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(0x2e73d5c?, {0x3339ac0?, 0xc00085eaa0?})
	/home/matzew/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1032 +0x47
knative.dev/func/pkg/app.Main()
	/home/matzew/go/src/knative.dev/func/pkg/app/app.go:40 +0x207
main.main()
	/home/matzew/go/src/knative.dev/func/cmd/func/main.go:6 +0xf

```

**Comment by matzew** [comment]
PR merged: https://github.com/knative/func/pull/2569
